"""Record every executed cell to a runnable notebook, for reproducibility.

Without this, the code an analysis actually ran survives only in the chat
transcript (prose and code interleaved, not runnable, inside a dotfile) and a
rotating debug log uncorrelated with projects. A collaborator handed
``outputs/figures/umap.png`` cannot re-derive it. This module writes
``outputs/analysis.ipynb`` — a normal, visible, openable artifact next to the
figures.

Design notes:

- **Hooked inside** :meth:`KernelClient.execute`, not in the ``python``/``r``
  tools. By the time a tool sees an ``ExecutionResult`` the text has already been
  truncated to ``MAX_OUTPUT_CHARS``; the notebook must record what really
  printed, so it has to run where the untruncated output still exists.
- **Read-modify-write per cell**, via a temp file + atomic replace. Slightly
  wasteful, but every cell is durable the moment it runs — which is the point,
  given that crashes are what we're guarding against. At a few hundred cells the
  rewrite is noise next to a kernel round-trip.
- **R cells** are recorded with an ``%%R`` marker. A ``.ipynb`` carries exactly
  one kernelspec, and Python dominates here, so R cells are preserved verbatim
  and clearly labelled rather than silently dropped or mislabelled as Python.
- **Never raises.** Logging must not break code execution. Same discipline as
  ``image_spill``.
"""

from __future__ import annotations

import logging
import os
import re
import threading
from pathlib import Path

from config import ACTIVE_PROJECT_DIR, PROJECT_OUTPUTS_DIRNAME

NOTEBOOK_FILENAME = "analysis.ipynb"

# ``data:image/png;base64,AAAA...`` → (mime, payload)
_DATA_URI_RE = re.compile(r"^data:(?P<mime>[^;]+);base64,(?P<data>.+)$", re.DOTALL)

# Serialize read-modify-write. The coding agent is single-threaded per run, but
# the server holds one KernelClient across sessions — two runs appending at once
# would otherwise interleave and lose cells.
_LOCK = threading.Lock()


def _notebook_path() -> Path:
    """Absolute path of the active project's analysis notebook."""
    return ACTIVE_PROJECT_DIR / PROJECT_OUTPUTS_DIRNAME / NOTEBOOK_FILENAME


def _new_notebook():
    """Create an empty notebook with a Python kernelspec and a provenance header."""
    import nbformat as nbf

    nb = nbf.v4.new_notebook()
    nb.metadata.kernelspec = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }
    nb.cells.append(
        nbf.v4.new_markdown_cell(
            "# Analysis notebook\n\n"
            "Auto-generated by TissueAgent: every cell below was executed by the "
            "coding agent, in order, against a persistent Jupyter kernel.\n\n"
            "**To re-run:** the cells below use paths relative to the *workspace "
            "root* (e.g. `project/outputs/figures/...`), which is the working "
            "directory the agent's kernel ran in. The setup cell below restores "
            "that cwd; without it, those paths resolve elsewhere and fail.\n\n"
            "Cells marked `%%R` ran in an R (IRkernel) session, not the Python "
            "kernel this notebook declares — rerun those in R.\n\n"
            "*Package versions are recorded below.*"
        )
    )
    # Restore the cwd the agent's kernel ran in: the *workspace root* (DATA_DIR),
    # not the project dir. The prompt directs the agent to write workspace-relative
    # paths like 'project/outputs/figures/x.png' precisely so kernel paths and the
    # file tools agree, so chdir'ing into project/ here would double the prefix.
    # The agent's own seeding is plumbing and never reaches the notebook, so
    # without this cell those paths break for anyone re-running it.
    #
    # The notebook lives at <workspace>/project/outputs/, so walk up two levels
    # from it rather than hardcoding an absolute path that won't survive being
    # copied to another machine.
    setup = nbf.v4.new_code_cell(
        "# Restore the agent's working directory (the workspace root).\n"
        "# Paths below are workspace-relative, e.g. 'project/outputs/figures/x.png'.\n"
        "import os\n"
        "if os.path.isdir('project'):\n"
        "    pass  # already at the workspace root\n"
        "elif os.path.basename(os.getcwd()) == 'outputs':\n"
        "    os.chdir('../..')  # notebook opened in place: <workspace>/project/outputs\n"
        "print('working directory:', os.getcwd())"
    )
    setup.execution_count = None
    nb.cells.append(setup)
    return nb


def _outputs_for(text: str, images: list[str], had_error: bool) -> list:
    """Build nbformat output objects for one cell's results."""
    import nbformat as nbf

    outputs = []
    if text:
        if had_error:
            # Record failures as plain text, not an `error` output: nbformat
            # requires ename/evalue/traceback fields we can't faithfully
            # reconstruct from the flattened stream text.
            outputs.append(nbf.v4.new_output("stream", name="stderr", text=text))
        else:
            outputs.append(nbf.v4.new_output("stream", name="stdout", text=text))

    for uri in images or []:
        m = _DATA_URI_RE.match(uri or "")
        if not m:
            continue
        mime = m.group("mime").strip().lower()
        outputs.append(nbf.v4.new_output("display_data", data={mime: m.group("data")}, metadata={}))
    return outputs


def append_cell(
    code: str,
    text: str,
    images: list[str] | None = None,
    language: str = "python",
    had_error: bool = False,
) -> None:
    """Append one executed cell and its outputs to the project's analysis notebook.

    Args:
        code: The source that was executed.
        text: The cell's full (untruncated) text output.
        images: Base64 ``data:`` URIs for any inline plots.
        language: ``"python"`` or ``"r"``.
        had_error: Whether the execution raised or timed out.

    Never raises: a failure to log must not fail the execution it is logging.
    """
    try:
        import nbformat as nbf

        source = code if language == "python" else f"%%R\n{code}"

        with _LOCK:
            path = _notebook_path()
            if path.exists():
                nb = nbf.read(str(path), as_version=4)
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                nb = _new_notebook()

            cell = nbf.v4.new_code_cell(source)
            cell.outputs = _outputs_for(text, images or [], had_error)
            # execution_count mirrors position, so a reader can see the order the
            # agent actually ran things in.
            cell.execution_count = sum(1 for c in nb.cells if c.cell_type == "code") + 1
            nb.cells.append(cell)

            # Atomic write: a crash mid-write must not corrupt the notebook.
            tmp = path.with_suffix(".ipynb.tmp")
            nbf.write(nb, str(tmp))
            os.replace(tmp, path)
    except Exception as e:  # pragma: no cover - defensive
        logging.warning(f"Could not append cell to analysis notebook: {e}")


def record_environment(execute_fn) -> None:
    """Capture package versions into the notebook, once per notebook.

    Takes a callable ``execute_fn(code, language) -> ExecutionResult`` and runs the
    probe *in the kernel* rather than importing here: the kernel is where the
    analysis actually runs, and its environment differs from the server's (Docker
    sandbox, or ``/opt/venv``).

    Without this, the same notebook silently yields different numbers under a
    different scanpy — the exact failure this module exists to prevent.
    """
    try:
        if _notebook_path().exists():
            return  # Already headed; versions were captured when it was created.

        probe = (
            "import sys, platform\n"
            "print('python', platform.python_version())\n"
            "for _m in ('numpy','pandas','scanpy','squidpy','anndata','matplotlib'):\n"
            "    try:\n"
            "        print(_m, __import__(_m).__version__)\n"
            "    except Exception as _e:\n"
            "        print(_m, 'unavailable')\n"
        )
        result = execute_fn(probe, "python")
        append_cell(
            probe,
            getattr(result, "text", "") or "",
            [],
            "python",
            bool(getattr(result, "error", False)),
        )
    except Exception as e:  # pragma: no cover - defensive
        logging.warning(f"Could not record environment in analysis notebook: {e}")
