#!/usr/bin/env python3
"""build_colormap.py -- produce the ONE colormap.yaml a reproduction plots from.

Part of the 'figure-reproduce' skill. Portable and self-contained: it imports NO
project package. Only PyYAML-free stdlib + numpy/Pillow (for the image tier) are
needed; anndata/h5py are used lazily for the dataset tier.

WHY THIS EXISTS
    Color has several possible sources of wildly different trustworthiness -- a
    user-supplied file, colors stored in the dataset, a reference figure's legend,
    or pixels sampled off a panel. Left implicit, the plotting code silently ends up
    on whichever one happened to be easiest, and nothing records which. This script
    tries them in priority order, writes ONE colormap.yaml, and stamps the tier it
    actually used so "colors came from the dataset" is never confused with "colors
    were guessed from a degraded raster".

TIERS (highest trust first)
    1 supplied    an existing palette file (--palette): user/authors' own mapping
    2 dataset     colors stored with the data (AnnData .uns["<key>_colors"])
    3 legend      swatches measured from a reference figure's legend
    4 pixels      dominant colors sampled off the panel  [ONLY if reliable]
    5 default     a named fallback palette -- a DEVIATION, never silent

    Categories and their ORDER come from the dataset whenever it has them
    (obs["<key>"].cat.categories), independent of where the colors came from.

USAGE
    python build_colormap.py -o colormap.yaml
        [--dataset data.h5ad --key celltype]     # categories + order (+ tier 2 colors)
        [--palette supplied.yaml]                # tier 1
        [--reference fig.png [--legend-box x0,y0,x1,y1]]   # tier 3 / 4
        [--allow-default]                        # permit tier 5 instead of failing

EXAMPLES
    # dataset supplies names+order, reference legend supplies colors
    python build_colormap.py --dataset adata.h5ad --key cell_type \
                             --reference fig2b.png -o colormap.yaml

    # user handed us the palette: it wins outright
    python build_colormap.py --palette uploads/colormap.yaml -o colormap.yaml

EXIT CODES
    0 wrote a colormap   1 no trustworthy source (use --allow-default to override)
    2 usage error
"""

from __future__ import annotations

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)


def hint(pkg: str) -> str:
    return f"[degraded] optional dependency '{pkg}' not installed - try: pip install {pkg}"


# --------------------------------------------------------------------------- #
# Minimal YAML I/O (a flat "key: value" mapping -- no PyYAML required)
# --------------------------------------------------------------------------- #
def read_simple_yaml(path: str) -> dict:
    """Read a flat mapping. Uses PyYAML when present, else a tolerant fallback."""
    text = open(path).read()
    try:
        import yaml
        data = yaml.safe_load(text)
        return data if isinstance(data, dict) else {}
    except ImportError:
        out = {}
        for line in text.splitlines():
            line = line.split("#", 1)[0].rstrip()
            if not line or line.startswith(("-", " ")) or ":" not in line:
                continue
            k, v = line.split(":", 1)
            out[k.strip().strip('"\'')] = v.strip().strip('"\'')
        return out


def write_colormap_yaml(path: str, mapping: dict, order: list, meta: dict) -> None:
    """Write colormap.yaml: provenance header, then `Category: "#hex"` in order."""
    L = ["# colormap.yaml -- the single source of truth for this figure's colors.",
         "# Generated by build_colormap.py. Plot from THIS file; do not re-derive",
         "# colors by eye and do not fall back to library defaults.",
         "#"]
    L.append("# source_tier : %s" % meta.get("tier"))
    L.append("# how         : %s" % meta.get("how"))
    if meta.get("order_from"):
        L.append("# order_from  : %s" % meta["order_from"])
    if meta.get("warnings"):
        for w in meta["warnings"]:
            L.append("# WARNING     : %s" % w)
    L.append("")
    for cat in order:
        if cat in mapping:
            L.append('%s: "%s"' % (cat, mapping[cat]))
    for cat in mapping:                      # any not covered by `order`
        if cat not in order:
            L.append('%s: "%s"' % (cat, mapping[cat]))
    open(path, "w").write("\n".join(L) + "\n")


# --------------------------------------------------------------------------- #
# Categories + order, and tier-2 colors, from the dataset
# --------------------------------------------------------------------------- #
def from_dataset(path: str, key: str | None):
    """Return (categories, colors_or_None, key_used, note).

    Reads AnnData via `anndata` when available, else directly from the HDF5 layout
    (an .h5ad is just HDF5, and the categorical encoding is stable enough to read
    without the library -- which matters because the plotting env often has anndata
    but a helper-script env may not).
    """
    try:
        import anndata  # noqa: F401
        return _from_dataset_anndata(path, key)
    except ImportError:
        pass
    try:
        import h5py  # noqa: F401
        return _from_dataset_h5py(path, key)
    except ImportError:
        return [], None, None, hint("anndata (or h5py)") + " -- dataset tier skipped"


def _pick_key(candidates: list, key: str | None):
    if key:
        return key if key in candidates else None
    for c in candidates:                     # prefer an obvious cell-type column
        if any(h in c.lower() for h in ("celltype", "cell_type", "annotation", "cluster", "leiden", "louvain")):
            return c
    return candidates[0] if len(candidates) == 1 else None


def _from_dataset_anndata(path: str, key: str | None):
    import anndata
    a = anndata.read_h5ad(path, backed="r")
    cats_cols = [c for c in a.obs.columns
                 if str(a.obs[c].dtype) == "category" and len(a.obs[c].cat.categories) <= 200]
    k = _pick_key(cats_cols, key)
    if k is None:
        return [], None, None, ("dataset has no single obvious categorical column; "
                                "pass --key (candidates: %s)" % ", ".join(cats_cols[:8]))
    cats = [str(c) for c in a.obs[k].cat.categories]
    colors = None
    ck = f"{k}_colors"
    if ck in a.uns and len(a.uns[ck]) == len(cats):
        colors = [str(c) for c in a.uns[ck]]
    return cats, colors, k, "read via anndata"


def _from_dataset_h5py(path: str, key: str | None):
    import h5py
    with h5py.File(path, "r") as f:
        if "obs" not in f:
            return [], None, None, "no /obs group in file"
        cand = []
        for name in f["obs"]:
            g = f["obs"][name]
            if isinstance(g, h5py.Group) and "categories" in g:
                cand.append(name)
        k = _pick_key(cand, key)
        if k is None:
            return [], None, None, ("no single obvious categorical column; pass --key "
                                    "(candidates: %s)" % ", ".join(cand[:8]))
        raw = f["obs"][k]["categories"][...]
        cats = [c.decode() if isinstance(c, bytes) else str(c) for c in raw]
        colors = None
        ck = f"{k}_colors"
        if "uns" in f and ck in f["uns"]:
            raw = f["uns"][ck][...]
            vals = [c.decode() if isinstance(c, bytes) else str(c) for c in raw]
            if len(vals) == len(cats):
                colors = vals
        return cats, colors, k, "read via h5py (anndata not installed)"


# --------------------------------------------------------------------------- #
# Colors from a reference figure (tiers 3 and 4)
# --------------------------------------------------------------------------- #
def from_reference(image: str, legend_box=None, max_colors: int = 40):
    """Return (entries, palette_reliability, note) using extract_reference_spec."""
    try:
        from PIL import Image
        import extract_reference_spec as ers
    except ImportError as exc:
        return [], {}, f"[degraded] cannot load the extractor ({exc})"
    try:
        img = Image.open(image).convert("RGB")
    except OSError as exc:
        return [], {}, f"cannot read reference '{image}': {exc}"

    box = legend_box or ers.autodetect_legend_box(img)
    entries, status = ([], "no legend region found") if box is None else \
        ers.find_legend_swatches(img, box, max_colors)

    import numpy as np
    px = np.asarray(img)
    flat = px.reshape(-1, 3)
    data = flat[~ers.is_chrome(flat)]
    rel = {}
    if len(data) > 100:
        ratio = len(np.unique(data, axis=0)) / float(len(data))
        rel = {"distinct_color_ratio": round(float(ratio), 3),
               "reliable": ratio <= 0.5}
    return entries, rel, status


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
DEFAULT_PALETTE = [   # Okabe-Ito (colorblind-safe) then tab10 -- only as tier 5
    "#e69f00", "#56b4e9", "#009e73", "#f0e442", "#0072b2", "#d55e00", "#cc79a7",
    "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b", "#e377c2",
    "#7f7f7f", "#bcbd22", "#17becf", "#aec7e8", "#ffbb78", "#98df8a",
]


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Build one colormap.yaml from the most trustworthy source available.",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--out", default="colormap.yaml", help="output path")
    ap.add_argument("--dataset", help=".h5ad providing categories + order (and maybe colors)")
    ap.add_argument("--key", help="obs column holding the categories")
    ap.add_argument("--palette", help="an existing palette file (tier 1, wins outright)")
    ap.add_argument("--reference", help="reference figure to read a legend from")
    ap.add_argument("--legend-box", help="x0,y0,x1,y1 of the legend in --reference")
    ap.add_argument("--allow-default", action="store_true",
                    help="permit the tier-5 default palette instead of failing")
    ap.add_argument("--json", action="store_true", help="also print the result as JSON")
    args = ap.parse_args()

    warnings: list[str] = []
    order: list[str] = []
    order_from = None

    # ---- categories + order (independent of the color source) ----
    ds_colors = None
    if args.dataset:
        cats, ds_colors, key_used, note = from_dataset(args.dataset, args.key)
        if cats:
            order, order_from = cats, f"dataset obs['{key_used}'] ({note})"
        else:
            warnings.append(f"dataset gave no categories: {note}")

    mapping: dict = {}
    tier = how = None

    # ---- tier 1: a supplied palette wins outright ----
    if args.palette:
        if not os.path.exists(args.palette):
            sys.stderr.write(f"ERROR: --palette '{args.palette}' not found\n")
            return 2
        supplied = read_simple_yaml(args.palette)
        supplied = {k: v for k, v in supplied.items() if isinstance(v, str) and v.startswith("#")}
        if supplied:
            mapping, tier, how = supplied, "1-supplied", f"user-supplied file {args.palette}"
            if not order:
                order, order_from = list(supplied), "supplied palette file"

    # ---- tier 2: colors stored with the data ----
    if not mapping and ds_colors and order and len(ds_colors) == len(order):
        mapping = dict(zip(order, ds_colors))
        tier, how = "2-dataset", f"AnnData uns['{args.key or 'auto'}_colors']"

    # ---- tiers 3/4: measured off the reference figure ----
    if not mapping and args.reference:
        box = None
        if args.legend_box:
            try:
                box = tuple(int(float(v)) for v in args.legend_box.split(","))
                assert len(box) == 4
            except (ValueError, AssertionError):
                sys.stderr.write("ERROR: --legend-box expects x0,y0,x1,y1\n")
                return 2
        entries, rel, note = from_reference(args.reference, box)
        labeled = [e for e in entries if e.get("label")]
        if labeled and (not order or len(labeled) == len(order)):
            keys = [e["label"] for e in labeled] if not order else order
            mapping = dict(zip(keys, [e["hex"] for e in labeled]))
            tier, how = "3-legend", f"legend swatches in {args.reference}"
            if not order:
                order, order_from = keys, "reference legend (top->bottom)"
        elif entries and order and len(entries) == len(order):
            # swatches found but unlabeled: order comes from the dataset, colors from
            # the legend's reading order. Only safe when the counts agree exactly.
            mapping = dict(zip(order, [e["hex"] for e in entries]))
            tier, how = "3-legend", f"legend swatches in {args.reference} (unlabeled; aligned by order)"
            warnings.append("legend swatches were unlabeled; colors aligned to dataset "
                            "category order -- VERIFY this pairing against the figure")
        elif entries and not order:
            # Swatches found, but we have neither OCR labels nor dataset categories to
            # name them. The colors and their ORDER are still measured facts, so emit
            # them under positional placeholders rather than discarding the one thing
            # the figure did tell us. The agent renames these from the panel.
            keys = ["category_%02d" % (i + 1) for i in range(len(entries))]
            mapping = dict(zip(keys, [e["hex"] for e in entries]))
            order, order_from = keys, "reference legend (top->bottom)"
            tier, how = "3-legend", f"legend swatches in {args.reference} (unlabeled, positional keys)"
            warnings.append(
                "swatch labels unavailable (no OCR and no --dataset): keys are "
                "POSITIONAL placeholders in the legend's reading order. Rename them to "
                "the panel's category names -- keep the order -- before plotting.")
        elif entries and order:
            warnings.append(
                "legend has %d swatches but the dataset has %d categories; refusing to "
                "guess the pairing. Pass --legend-box to tighten the crop, or supply "
                "--palette." % (len(entries), len(order)))
        else:
            if not rel.get("reliable", False):
                warnings.append(
                    "reference palette is NOT reliably recoverable "
                    f"(distinct_color_ratio={rel.get('distinct_color_ratio')}, >0.5 means "
                    "sub-pixel/compressed markers): pixel sampling was refused")
            else:
                warnings.append(f"no usable legend in {args.reference}: {note}")

    # ---- tier 5: a documented default, never silent ----
    if not mapping:
        if not args.allow_default:
            sys.stderr.write(
                "ERROR: no trustworthy color source.\n"
                "  Tried: --palette (tier 1), dataset uns colors (tier 2), "
                "reference legend (tier 3).\n"
                "  Colors sampled off a dense/compressed panel are refused on purpose "
                "-- they are not recoverable.\n"
                "  Fix by supplying one of:\n"
                "    --palette <file>            the authors'/user's own mapping\n"
                "    --reference <fig> --legend-box x0,y0,x1,y1   if a legend exists\n"
                "  Or re-run with --allow-default to assign a documented fallback "
                "palette (records a DEVIATION).\n")
            for w in warnings:
                sys.stderr.write(f"  note: {w}\n")
            return 1
        if not order:
            sys.stderr.write("ERROR: --allow-default needs categories; pass --dataset/--key.\n")
            return 2
        mapping = {c: DEFAULT_PALETTE[i % len(DEFAULT_PALETTE)] for i, c in enumerate(order)}
        tier, how = "5-default", "fallback palette (Okabe-Ito + tab10)"
        warnings.append("DEVIATION: colors are a default palette, NOT the target's. "
                        "Record this in the repro note.")

    meta = {"tier": tier, "how": how, "order_from": order_from, "warnings": warnings}
    if not order:
        order = list(mapping)
    write_colormap_yaml(args.out, mapping, order, meta)

    print(f"wrote {args.out}")
    print(f"  tier       : {tier}")
    print(f"  how        : {how}")
    print(f"  categories : {len(mapping)}" + (f"  (order from {order_from})" if order_from else ""))
    for w in warnings:
        print(f"  WARNING    : {w}")
    if args.json:
        print(json.dumps({"tier": tier, "how": how, "order": order,
                          "colormap": mapping, "warnings": warnings}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
